// ** MUI Imports
import Grid from '@mui/material/Grid';

import { useTranslation } from 'react-i18next';
import { InlineWidget } from 'react-calendly';
import { IWorker } from 'src/types/@autogenerated';
import { Typography } from '@mui/material';

const IntroductionStep = () => {
  // ** Hooks
  const { t } = useTranslation();

  // ** State

  return (
    <Grid container spacing={6}>
      <Grid item xs={12}>
        <Typography variant='h2' sx={{ fontWeight: 'bold', fontSize: 30, width: '100%', textAlign: 'center' }}>
          {t('Patient triage')}
        </Typography>
        <InlineWidget url='https://calendly.com/anajmoura/entrevista-de-admissao' />
      </Grid>
    </Grid>
  );
};

export default IntroductionStep;
