// formik components

import Button from '@mui/material/Button';
import Card from '@mui/material/Card';
import CardHeader from '@mui/material/CardHeader';
import { useEffect, useState } from 'react';
import Icon from 'src/@core/components/icon';
import Loader from 'src/@core/components/loader';
import {
  getSourceEntityData,
  handleError,
  nameof,
  parseDateToDateTimeString,
  splitByUppercase,
  hasRole,
} from 'src/@core/coreHelper';
import { IEntitySchema, IEntitySchemaField, IEntitySchemaWithFields, ISelectOptionEntity } from 'src/types/entities';

import { DataGrid, GridColDef } from '@mui/x-data-grid';

import Box from '@mui/material/Box';
import Typography from '@mui/material/Typography';
import CustomChip from 'src/@core/components/mui/chip';

import { useRouter } from 'next/router';

import { CardContent, Divider, Grid, IconButton, MenuItem, Tooltip, capitalize } from '@mui/material';
import { ThemeColor } from 'src/@core/layouts/types';

import Fuse from 'fuse.js';
import { useTranslation } from 'react-i18next';
import CustomAvatar from 'src/@core/components/mui/avatar';
import CustomTextField from 'src/@core/components/mui/text-field';
import { getInitials } from 'src/@core/utils/get-initials';
import { useDynamics } from 'src/hooks/useDynamics';
import { dynamicGet } from 'src/services/entitiesDynamicServices';
import {
  PaymentConditionStateTypes,
  IApplicant,
  ICompany,
  IPatient,
  IPatientPaymentCondition,
} from 'src/types/@autogenerated';
import { CMSCollections } from 'src/types/@autogenerated';
import { useCurrentUser } from 'src/hooks/useCurrentUser';
import { UserDefinedRols } from 'src/types/userDefinedRols';
import { AppRols } from 'src/types/appRols';
import { formatDate } from 'src/@core/utils/format';
import { object } from 'yup';

const ITEM_HEIGHT = 48;
const ITEM_PADDING_TOP = 8;

const MenuProps = {
  PaperProps: {
    style: {
      width: 250,
      maxHeight: ITEM_HEIGHT * 4.5 + ITEM_PADDING_TOP,
    },
  },
};

const SCHEMA_NAME = CMSCollections.PATIENT_PAYMENT_CONDITIONS;
const PATIENT_SCHEMA = CMSCollections.PATIENTS;

interface IPatientPaymentConditionRow extends IPatientPaymentCondition {
  showRow?: boolean;
  company: ICompany;
  patient: IPatient;
  patientName: string;
  companyName: string;
}

interface CellType {
  row: IPatientPaymentConditionRow;
}

const PaymentConditionsList = ({}) => {
  // ** Hooks
  const router = useRouter();
  const dynamics = useDynamics();
  const { t } = useTranslation();
  const currentUser = useCurrentUser();

  // ** State
  const [entitySchema, setEntitySchema] = useState<IEntitySchema | null>(null);
  const [entitySchemaFields, setEntitySchemaFields] = useState<IEntitySchemaField[]>([]);

  const [entitiesData, setEntitiesData] = useState<IPatientPaymentConditionRow[]>([]);

  const [loadingSchema, setLoadingSchema] = useState<boolean>(true);
  const [loadingData, setLoadingData] = useState<boolean>(false);

  const [isFirstLoad, setIsFirstLoad] = useState<boolean>(true);

  const [paginationModel, setPaginationModel] = useState({ page: 0, pageSize: 100 });

  const [columns, setColumns] = useState<GridColDef[]>([]);

  const [searchText, setSearchText] = useState<string>('');

  const [paymentConditionsStateTypeOptions, setPaymentConditionsStateTypeOptions] = useState<ISelectOptionEntity[]>([]);

  const [selectedPaymentConditionTypeOptions, setSelectedPaymentConditionTypeOptions] = useState<string[]>([
    PaymentConditionStateTypes.ACTIVE,
    PaymentConditionStateTypes.NEAR_EXPIRY,
    PaymentConditionStateTypes.EXPIRED,
  ]);

  const PAYMENT_CONDITION_STATE_TYPE_PROP_NAME = 'paymentConditionsState';

  const isPermittedByRol = () => {
    return (
      !currentUser.isLoading &&
      !!currentUser.currentUser &&
      (hasRole(currentUser.currentUser?.appRols, AppRols.APP_ADMIN) ||
        hasRole(currentUser.currentUser?.userDefinedRols, UserDefinedRols.UDR_STAFF_COMMERCIAL))
    );
  };

  // ** Effects
  useEffect(() => {
    const doAsync = async () => {
      try {
        setLoadingSchema(true);
        if (dynamics.isLoadingSchemas || !dynamics.entitySchemas || !dynamics.entitySchemasFields) return null;

        const schema = dynamics.entitySchemas.find((schema) => {
          return schema.name === SCHEMA_NAME;
        });
        if (!schema) throw new Error('Missing schemaName: ' + SCHEMA_NAME);

        const schemaFields = dynamics.entitySchemasFields.filter((field) => {
          return field.schemaId === schema.id;
        });

        // Fetch Schema
        // const entitySchemaResponse = (await getEntitySchemaByName(schemaName)) as IEntitySchemaWithFields;
        const entitySchemaResponse: IEntitySchemaWithFields = { ...schema, fields: schemaFields };

        setEntitySchema(entitySchemaResponse);
        setEntitySchemaFields(
          entitySchemaResponse.fields.sort((a, b) => {
            return a.order - b.order;
          })
        );

        setLoadingSchema(false);
      } catch (e: any) {
        handleError(e);
        setLoadingSchema(false);
      }
    };

    doAsync();

    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [dynamics.isLoadingSchemas]);

  // define columns and filters
  useEffect(() => {
    const doAsync = async () => {
      try {
        if (!entitySchema || !entitySchemaFields) return;

        // Define table columns
        updateColumnsData();
        // define filters options
        const field = entitySchemaFields.find((field) => {
          return field.name === PAYMENT_CONDITION_STATE_TYPE_PROP_NAME;
        });

        if (field && field.relationshipSchemaId && dynamics.entitySchemas) {
          const relatedSchema = dynamics.entitySchemas.find((schema) => {
            return schema.id === field.relationshipSchemaId;
          });

          if (relatedSchema) {
            const optionsData: any = await dynamicGet({ params: '/cms/' + relatedSchema.name });

            setPaymentConditionsStateTypeOptions(optionsData.items as ISelectOptionEntity[]);
          }
        }
      } catch (e: any) {
        handleError(e);
      }
    };

    doAsync();
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [entitySchema, entitySchemaFields]);

  // Fetch schema.collectionName
  useEffect(() => {
    const doAsync = async () => {
      try {
        if (!entitySchema || !entitySchemaFields) return;

        // Define table columns
        updateColumnsData();

        setLoadingData(true);

        // load entity data
        console.log('Filtro', PAYMENT_CONDITION_STATE_TYPE_PROP_NAME);
        console.log('Valores', selectedPaymentConditionTypeOptions);
        const paymentConditionsResponse: any = await dynamicGet({
          params: '/cms/' + entitySchema.name,
          filters: [
            {
              key: PAYMENT_CONDITION_STATE_TYPE_PROP_NAME,
              value: selectedPaymentConditionTypeOptions,
              operator: '$in',
            },
          ],
        });

        const paymentConditions = paymentConditionsResponse.items as IPatientPaymentCondition[];
        console.log(paymentConditions);
        setEntitiesData(
          paymentConditions.map((item: IPatientPaymentCondition) => {
            const company = getSourceEntityData({
              obj: item,
              key: nameof<IPatientPaymentCondition>('healthInsuranceId'),
            });
            const patient = getSourceEntityData({
              obj: item,
              key: nameof<IPatientPaymentCondition>('userId'),
            });

            return {
              ...item,
              showRow: true,
              company,
              patient,
              patientName: patient.firstName + ' ' + patient.lastName,
              companyName: company.name,
            } as IPatientPaymentConditionRow;
          }) as IPatientPaymentConditionRow[]
        );

        setLoadingData(false);
      } catch (e: any) {
        setLoadingData(false);
        handleError(e);
      }
    };

    doAsync();
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [entitySchema, entitySchemaFields, selectedPaymentConditionTypeOptions]);

  useEffect(() => {
    const doAsync = async () => {
      try {
        if (isFirstLoad) {
          setIsFirstLoad(false);

          return;
        }

        if (!entitySchema) return;

        setLoadingData(true);
        if (searchText) {
          const searchByProps = [
            nameof<IPatientPaymentConditionRow>('patientName'),
            nameof<IPatientPaymentConditionRow>('companyName'),
          ];
          const fuse = new Fuse(entitiesData, {
            threshold: 0.3,
            // minMatchCharLength: 2,
            keys: searchByProps,
          });

          const auxFilteredItems = fuse.search(searchText);

          const filteredItems = auxFilteredItems.map((element: any) => {
            return { ...element.item, showRow: true };
          });

          setEntitiesData(
            entitiesData.map((item) => {
              if (
                filteredItems.find((fi) => {
                  return fi.id === item.id;
                })
              ) {
                return { ...item, showRow: true };
              }

              return { ...item, showRow: false };
            })
          );
        } else {
          setEntitiesData(
            entitiesData.map((item) => {
              return { ...item, showRow: true };
            })
          );
        }
        setLoadingData(false);
      } catch (e) {
        setLoadingData(false);
        handleError(e);
      }
    };

    doAsync();
  }, [searchText]);

  const updateColumnsData = () => {
    // TODO - aca podria jugar con una coleccion de 'layouts' donde defina las cols a mostrar
    // TODO - Los layouts podrian definir si se usan tablas o cards, y las cards que prop usar para cada campo en caso de
    // TODO - incluso las cards podrian ser de estructuras template o creadas por el usuario (designer)
    // TODO - Tmb podria jugar con campos virtuales que puedan ser funciones a lo excel o estáticos
    const columnsData: GridColDef[] = [];

    // icons col
    columnsData.push({
      flex: 0.1,
      minWidth: 110,
      field: 'icons',
      headerName: '',

      renderCell: ({ row }: CellType) => (
        <Box sx={{ display: 'flex', alignItems: 'center' }}>
          <Tooltip title='View Content'>
            <IconButton
              size='small'
              sx={{ color: 'text.secondary' }}
              onClick={() => {
                router.push(`/${SCHEMA_NAME}/${row.id}`);
              }}
            >
              <Icon icon='tabler:eye' />
            </IconButton>
          </Tooltip>
        </Box>
      ),
    });

    columnsData.push({
      flex: 0.2,
      minWidth: 110,
      field: 'name',
      headerName: t('name') as string,

      renderCell: ({ row }: CellType) => {
        return (
          <>
            <CustomAvatar
              skin='light'
              color={'primary'}
              sx={{
                mr: 2.5,
                width: 38,
                height: 38,
                fontWeight: 500,
                fontSize: (theme) => theme.typography.body1.fontSize,
              }}
            >
              {getInitials((row.patient.firstName + ' ' + row.patient.lastName).toUpperCase())}
            </CustomAvatar>

            <Box sx={{ display: 'flex', alignItems: 'flex-start', flexDirection: 'column' }}>
              <Typography
                noWrap
                // component={Link}
                // href='/apps/user/view/account'
                sx={{
                  fontWeight: 500,
                  textDecoration: 'none',
                  color: 'text.secondary',
                  textTransform: 'capitalize',
                }}
              >
                {row.patient.firstName + ' ' + row.patient.lastName}
              </Typography>
              {/* {row.contactEmail && (
                <Typography noWrap variant='body2' sx={{ color: 'text.disabled' }}>
                  {row.contactEmail}
                </Typography>
              )} */}
            </Box>
          </>
        );
      },
    });

    columnsData.push({
      flex: 0.2,
      minWidth: 110,
      field: 'insurance',
      headerName: t('insurance') as string,

      renderCell: ({ row }: CellType) => {
        return (
          <Box sx={{ display: 'flex', alignItems: 'flex-start', flexDirection: 'column' }}>
            <Typography
              noWrap
              // component={Link}
              // href='/apps/user/view/account'
              sx={{
                fontWeight: 500,
                textDecoration: 'none',
                color: 'text.secondary',
                textTransform: 'capitalize',
              }}
            >
              {row.company.name}
            </Typography>
            {row.company.contactEmail && (
              <Typography noWrap variant='body2' sx={{ color: 'text.disabled' }}>
                {row.company.contactEmail}
              </Typography>
            )}
          </Box>
        );
      },
    });

    columnsData.push({
      flex: 0.2,
      minWidth: 110,
      field: 'state',
      headerName: t('state') as string,

      renderCell: ({ row }: CellType) => {
        return (
          <Box sx={{ display: 'flex', alignItems: 'center' }}>
            <Typography
              noWrap
              // component={Link}
              // href='/apps/user/view/account'
              sx={{
                fontWeight: 500,
                textDecoration: 'none',
                color: 'text.secondary',
                textTransform: 'capitalize',
              }}
            >
              {t(`${row.paymentConditionsState}`)}
            </Typography>
          </Box>
        );
      },
    });

    columnsData.push({
      flex: 0.2,
      minWidth: 110,
      field: 'dueDate',
      headerName: t('due date') as string,

      renderCell: ({ row }: CellType) => {
        return (
          <Box sx={{ display: 'flex', alignItems: 'center' }}>
            <Box sx={{ display: 'flex', flexDirection: 'column' }}>
              <Typography sx={{ fontWeight: 500, color: 'text.secondary' }}>
                {row.validUntil ? formatDate(row.validUntil) : '-'}
              </Typography>
            </Box>
          </Box>
        );
      },
    });

    setColumns(columnsData);
  };

  const handlePaymentConditionStateTypeOptionsChange = (newValues: string[]) => {
    setSelectedPaymentConditionTypeOptions(newValues);
  };
  // const handleSearchFilter = (newText: string) => {};

  if (!entitySchema || !entitySchemaFields || loadingSchema) return <Loader />;

  return (
    <>
      <Card>
        <CardHeader sx={{ textTransform: 'capitalize' }} title={t(splitByUppercase(entitySchema.name))} />
        <CardContent>
          <Grid container spacing={6}>
            <Grid item sm={4} xs={12}></Grid>
          </Grid>
        </CardContent>
        {paymentConditionsStateTypeOptions && (
          <CustomTextField
            select
            fullWidth
            label={t('status')}
            SelectProps={{
              MenuProps,
              multiple: true,
              value: selectedPaymentConditionTypeOptions,
              onChange: (e) => {
                console.log(e.target.value);
                handlePaymentConditionStateTypeOptionsChange(e.target.value as string[]);
              },
              renderValue: (selected) => (
                <Box sx={{ display: 'flex', flexWrap: 'wrap' }}>
                  {(selected as unknown as string[]).map((value) => {
                    const typeOption = paymentConditionsStateTypeOptions.find((option) => {
                      return option.code === value;
                    });
                    if (!typeOption) return '-';

                    return (
                      <CustomChip
                        key={typeOption.code}
                        label={capitalize(t(typeOption.name))}
                        sx={{ m: 0.75 }}
                        skin='light'
                        color='primary'
                      />
                    );
                  })}
                </Box>
              ),
            }}
          >
            {paymentConditionsStateTypeOptions.map((selectOption, index) => (
              <MenuItem key={index} value={selectOption.code}>
                {capitalize(t(selectOption.name))}
              </MenuItem>
            ))}
          </CustomTextField>
        )}
        <Divider sx={{ m: '0 !important' }} />
        <Box
          sx={{
            py: 4,
            px: 6,
            rowGap: 2,
            columnGap: 4,
            display: 'flex',
            flexWrap: 'wrap',
            alignItems: 'center',

            // justifyContent: 'space-between',
            justifyContent: 'right',
          }}
        >
          {/* <Button color='secondary' variant='tonal' startIcon={<Icon icon='tabler:upload' />}>
        Export
      </Button> */}
          <Box sx={{ rowGap: 2, display: 'flex', flexWrap: 'wrap', alignItems: 'center' }}>
            <CustomTextField
              sx={{ mr: 4 }}
              placeholder={`${capitalize(t('search placeholder'))}`}
              onChange={(e) => setSearchText(e.target.value)}
            />
            {/* {isPermittedByRol() && (
              <Button
                onClick={() => {
                  router.push('/');
                }}
                variant='contained'
                sx={{ '& svg': { mr: 2 } }}
              >
                <Icon fontSize='1.125rem' icon='tabler:plus' />
                {capitalize(t('new'))}
              </Button>
            )} */}
          </Box>
        </Box>

        <DataGrid
          autoHeight
          rows={entitiesData.filter((item) => {
            return item.showRow;
          })}
          rowHeight={60}
          loading={loadingData}
          columns={columns}
          initialState={{
            columns: {
              columnVisibilityModel: {
                id: false,
              },
            },
          }}
          disableRowSelectionOnClick
          pageSizeOptions={[7, 10, 25, 50]}
          paginationModel={paginationModel}
          onPaginationModelChange={setPaginationModel}
        />
      </Card>
    </>
  );
};

export default PaymentConditionsList;
