// ** MUI Components
import Box from '@mui/material/Box';
import Grid from '@mui/material/Grid';
import Card from '@mui/material/Card';
import Typography from '@mui/material/Typography';
import CardContent from '@mui/material/CardContent';

// ** Icon Imports
import Icon from 'src/@core/components/icon';

// ** Types
import { ProfileTeamsType, ProfileTabCommonType } from 'src/types';
import { IUser } from 'src/types/users';
import { IUsersAddress } from 'src/types/@autogenerated';

interface PropsType {
  user: IUser;
  addresses: IUsersAddress[];
}

const AboutOverivew = ({ user, addresses }: PropsType) => {
  const renderUserBasicData = () => {
    return (
      <>
        <Box
          sx={{
            display: 'flex',
            '&:not(:last-of-type)': { mb: 3 },
            '& svg': { color: 'text.secondary' },
          }}
        >
          <Box sx={{ display: 'flex', mr: 2 }}>
            <Icon fontSize='1.25rem' icon={'tabler:user'} />
          </Box>

          <Box sx={{ columnGap: 2, display: 'flex', flexWrap: 'wrap', alignItems: 'center' }}>
            <Typography sx={{ color: 'text.secondary' }}>{user.firstName + ' ' + user.lastName}</Typography>
          </Box>
        </Box>

        <Box
          sx={{
            display: 'flex',
            '&:not(:last-of-type)': { mb: 3 },
            '& svg': { color: 'text.secondary' },
          }}
        >
          <Box sx={{ display: 'flex', mr: 2 }}>
            <Icon fontSize='1.25rem' icon={'tabler:mail'} />
          </Box>

          <Box sx={{ columnGap: 2, display: 'flex', flexWrap: 'wrap', alignItems: 'center' }}>
            <Typography sx={{ color: 'text.secondary' }}>{user.email}</Typography>
          </Box>
        </Box>
      </>
    );
  };

  const renderAddresses = () => {
    if (!addresses || !addresses.length) return <>No address</>;

    return addresses.map((item, index) => {
      return (
        <Box
          key={index}
          sx={{
            display: 'flex',
            alignItems: 'center',
            '&:not(:last-of-type)': { mb: 3 },
            // '& svg': { color: `${item.}.main` },
          }}
        >
          <Icon fontSize='1.25rem' icon={'tabler:map'} />

          <Typography sx={{ mx: 2, fontWeight: 500, color: 'text.secondary' }}>{item.address.addressString}</Typography>
        </Box>
      );
    });
  };

  return (
    <Grid container spacing={6}>
      <Grid item xs={12}>
        <Card>
          <CardContent>
            <Box sx={{ mb: 6 }}>
              <Typography variant='body2' sx={{ mb: 4, color: 'text.disabled', textTransform: 'uppercase' }}>
                About
              </Typography>
              {renderUserBasicData()}
            </Box>

            <Box sx={{ mb: 6 }}>
              <Typography variant='body2' sx={{ mb: 4, color: 'text.disabled', textTransform: 'uppercase' }}>
                Addresses
              </Typography>
              {renderAddresses()}
            </Box>
            {/* <div>
              <Typography variant='body2' sx={{ mb: 4, color: 'text.disabled', textTransform: 'uppercase' }}>
                Teams
              </Typography>
              {renderTeams(teams)}
            </div> */}
          </CardContent>
        </Card>
      </Grid>
    </Grid>
  );
};

export default AboutOverivew;
