// ** React Imports
import { useState, useEffect } from 'react';

// ** MUI Components
import Box from '@mui/material/Box';
import Grid from '@mui/material/Grid';
import Button from '@mui/material/Button';

// ** Icon Imports
import Icon from 'src/@core/components/icon';
// ** Custom Components Imports
import CustomTextField from 'src/@core/components/mui/text-field';
// ** Styles Import
import 'react-credit-cards/es/styles-compiled.css';
import { Form, Formik } from 'formik';
import * as Yup from 'yup';
import DynamicFormComponent from 'src/views/components/dynamics/DynamicFormComponent';
import { DynamicComponentTypes, IForm } from 'src/types/dynamics';
import { useTranslation } from 'react-i18next';
import { MenuItem, capitalize } from '@mui/material';
import {
  CMSCollections,
  IWorker,
  WorkerAgePreferences,
  WorkerEducationalLevels,
  PathologiesTypes,
  WorkerStateTypes,
  WorkerYearsExperienceOptions,
} from 'src/types/@autogenerated';
import Loader from 'src/@core/components/loader';
import { dynamicGet } from 'src/services/entitiesDynamicServices';
import { DEFAULT_ORGANIZATION_ID } from 'src/configs/appConfig';
import * as yup from 'yup';
import { nameof } from 'src/@core/coreHelper';

const STEP_VALIDATIONS = Yup.object().shape({
  yearsExperience: yup.string().required(),
  educationalLevel: yup.string().required(),
  pathologiesExperience: yup.array().of(yup.string()).required(),
});

const MenuProps = {
  PaperProps: {
    style: {
      width: 250,
      maxHeight: 48 * 4.5 + 8,
    },
  },
};

interface props {
  handlePrev: () => void;
  entityData: IWorker;
  onSubmit: (formData: any, isReload: boolean) => Promise<any>;
}
const JobExperienceStep = ({ handlePrev, entityData, onSubmit }: props) => {
  //**  hooks
  const { t } = useTranslation();

  // ** State
  const [isCreating, setIsCreating] = useState<boolean>(true);
  const [submitError, setSubmitError] = useState<any>(null);
  const [initialValues, setInitialValues] = useState<IWorker>(entityData);
  const [pathologiesExperienceOptions, setPathologiesExperienceOptions] = useState<any[]>([]);
  const [educationalLevelOptions, setEducationalLevelOptions] = useState<any[]>([]);
  const [yearsExperienceOptions, setYearsExperienceOptions] = useState<any[]>([]);
  const [pathologiesPreferenceOptions, setPathologiesPreferenceOptions] = useState<any[]>([]);
  const [agePreferenceOptions, setAgePreferenceOptions] = useState<any[]>([]);

  const [loadingOptions, setLoadingOptions] = useState<boolean>(true);

  const getOptions = async (schema: string) => {
    try {
      //check this
      const optionsData: any = await dynamicGet({ params: '/cms/public/' + DEFAULT_ORGANIZATION_ID + '/' + schema });

      return optionsData.items;
    } catch (error) {
      return [];
    }
  };
  // ** Effects
  useEffect(() => {
    const doAsync = async () => {
      try {
        setLoadingOptions(true);
        setPathologiesExperienceOptions(await getOptions(CMSCollections.PATHOLOGIES_TYPES));
        setEducationalLevelOptions(await getOptions(CMSCollections.WORKER_EDUCATIONAL_LEVELS));
        setYearsExperienceOptions(await getOptions(CMSCollections.WORKER_YEARS_EXPERIENCE_OPTIONS));
        setPathologiesPreferenceOptions(await getOptions(CMSCollections.PATHOLOGIES_TYPES));
        setAgePreferenceOptions(await getOptions(CMSCollections.WORKER_AGE_PREFERENCES));
        setLoadingOptions(false);
      } catch (error) {}
    };

    doAsync();
  }, []);
  const handleSubmit = async (values: any, actions: any) => {
    try {
      setSubmitError(null);
      actions.setSubmitting(true);

      // clono para no modificar el original del form
      const itemValues = { ...values };

      const keys = Object.keys(itemValues);

      keys.forEach((key) => {
        const itemValue = itemValues[key];

        if (!itemValue.isOptionField) return;

        itemValues[key] = itemValue.value;
      });

      //actuliza el state del worker en el form
      itemValues[nameof<IWorker>('workerState')] = WorkerStateTypes.PENDING_PREFERENCES;
      onSubmit(itemValues, false);

      actions.setSubmitting(false);
    } catch (e) {
      setSubmitError(e);
      actions.setSubmitting(false);
    }
  };

  return (
    <>
      <Formik
        enableReinitialize={true}
        initialValues={initialValues}
        validationSchema={STEP_VALIDATIONS}
        onSubmit={handleSubmit}
      >
        {({ values, errors, touched, isSubmitting, setValues }) => (
          <Form id={'stepExperienceWorkerForm'} autoComplete='off'>
            <Grid item sm={6} md={6} xs={6}>
              <Grid container spacing={5} sx={{ mb: 4 }}>
                <Grid item xs={12} sm={6}>
                  {loadingOptions ? (
                    <Loader />
                  ) : (
                    <CustomTextField
                      select
                      fullWidth
                      label={t('educationalLevel') as string}
                      id='educationalLevel'
                      value={values.educationalLevel ?? ''}
                      error={errors && errors['educationalLevel'] ? true : false}
                      helperText={errors['educationalLevel'] ? (t('field required msj') as string) : ''}
                      onChange={(e) =>
                        setValues({
                          ...values,
                          educationalLevel: e.target.value as WorkerEducationalLevels,
                        })
                      }
                    >
                      {educationalLevelOptions.map((item: any, index: any) => {
                        return (
                          <MenuItem key={index} value={item.code}>
                            {capitalize(t(item.name))}
                          </MenuItem>
                        );
                      })}
                    </CustomTextField>
                  )}
                </Grid>
                <Grid item xs={12} sm={6}>
                  <DynamicFormComponent
                    component={{
                      id: 'certificates',
                      name: 'certificates',
                      label: t('degree certificates') as string,
                      placeholder: t('degree certificates placeholder') as string,
                      type: DynamicComponentTypes.FORM_TEXT,
                      dimensions: { xs: 12, sm: 12 },
                    }}
                    isCreating={isCreating}
                  />
                </Grid>
                <Grid item xs={12} sm={6}>
                  {loadingOptions ? (
                    <Loader />
                  ) : (
                    <CustomTextField
                      select
                      fullWidth
                      label={t('pathologiesExperience') as string}
                      id='pathologiesExperience'
                      name='pathologiesExperience'
                      error={errors && errors['pathologiesExperience'] ? true : false}
                      helperText={errors['pathologiesExperience'] ? (t('field required msj') as string) : ''}
                      value={values.pathologiesExperience ?? []}
                      SelectProps={{
                        MenuProps,
                        multiple: true,
                        value: values.pathologiesExperience ?? [],
                        onChange: (e) =>
                          setValues({ ...values, pathologiesExperience: e.target.value as PathologiesTypes[] }, true),
                        renderValue: (selected: any) => {
                          const newVal = [...selected] as string[];

                          return newVal
                            .map((item) => {
                              return capitalize(t(item));
                            })
                            .join(', ');
                        },
                      }}
                    >
                      {pathologiesExperienceOptions.map((item: any, index: any) => {
                        return (
                          <MenuItem key={index} value={item.code}>
                            {capitalize(t(item.name))}
                          </MenuItem>
                        );
                      })}
                    </CustomTextField>
                  )}
                </Grid>
                <Grid item xs={12} sm={6}>
                  {loadingOptions ? (
                    <Loader />
                  ) : (
                    <CustomTextField
                      select
                      fullWidth
                      label={t('yearsExperience') as string}
                      id='yearsExperience'
                      value={values.yearsExperience ?? ''}
                      error={errors && errors['yearsExperience'] ? true : false}
                      helperText={errors['yearsExperience'] ? (t('field required msj') as string) : ''}
                      onChange={(e) =>
                        setValues({ ...values, yearsExperience: e.target.value as WorkerYearsExperienceOptions })
                      }
                    >
                      {yearsExperienceOptions.map((item: any, index: any) => {
                        return (
                          <MenuItem key={index} value={item.code}>
                            {capitalize(t(item.name))}
                          </MenuItem>
                        );
                      })}
                    </CustomTextField>
                  )}
                </Grid>
                <Grid item xs={12} sm={6}>
                  {loadingOptions ? (
                    <Loader />
                  ) : (
                    <CustomTextField
                      select
                      fullWidth
                      label={t('pathologiesPreference') as string}
                      id='pathologiesPreference'
                      name='pathologiesPreference'
                      error={errors && errors['pathologiesPreference'] ? true : false}
                      helperText={errors['pathologiesPreference'] ? (t('field required msj') as string) : ''}
                      value={values.pathologiesPreference ?? []}
                      SelectProps={{
                        MenuProps,
                        multiple: true,
                        value: values.pathologiesPreference ?? [],
                        onChange: (e) =>
                          setValues({ ...values, pathologiesPreference: e.target.value as PathologiesTypes[] }, true),
                        renderValue: (selected: any) => {
                          const newVal = [...selected] as string[];

                          return newVal
                            .map((item) => {
                              return capitalize(t(item));
                            })
                            .join(', ');
                        },
                      }}
                    >
                      {pathologiesPreferenceOptions.map((item: any, index: any) => {
                        return (
                          <MenuItem key={index} value={item.code}>
                            {capitalize(t(item.name))}
                          </MenuItem>
                        );
                      })}
                    </CustomTextField>
                  )}
                </Grid>
                <Grid item xs={12} sm={6}>
                  {loadingOptions ? (
                    <Loader />
                  ) : (
                    <CustomTextField
                      select
                      fullWidth
                      label={t('agePreference') as string}
                      id='agePreference'
                      name='agePreference'
                      error={errors && errors['agePreference'] ? true : false}
                      helperText={errors['agePreference'] ? (t('field required msj') as string) : ''}
                      value={values.pathologiesExperience ?? []}
                      SelectProps={{
                        MenuProps,
                        multiple: true,
                        value: values.agePreference ?? [],
                        onChange: (e) =>
                          setValues({ ...values, agePreference: e.target.value as WorkerAgePreferences[] }, true),
                        renderValue: (selected: any) => {
                          const newVal = [...selected] as string[];

                          return newVal
                            .map((item) => {
                              return capitalize(t(item));
                            })
                            .join(', ');
                        },
                      }}
                    >
                      {agePreferenceOptions.map((item: any, index: any) => {
                        return (
                          <MenuItem key={index} value={item.code}>
                            {capitalize(t(item.name))}
                          </MenuItem>
                        );
                      })}
                    </CustomTextField>
                  )}
                </Grid>
              </Grid>
            </Grid>

            <Grid item xs={12} sx={{ pt: (theme) => `${theme.spacing(6)} !important` }}>
              <Box sx={{ display: 'flex', justifyContent: 'right' }}>
                <Button variant='contained' type='submit' disabled={isSubmitting} sx={{ '& svg': { ml: 2 } }}>
                  {capitalize(t('next') as string)}
                  <Icon fontSize='1.125rem' icon='tabler:arrow-right' />
                </Button>
              </Box>
            </Grid>
          </Form>
        )}
      </Formik>
    </>
  );
};

export default JobExperienceStep;
